name: Java CI with Maven

on:
  push:
    branches: [ "feature" ]

jobs:
  deploy_maven_docker:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: update version
      run: |
          current_version=$(grep -m1 '<version>.*</version>' pom.xml | sed -E 's/<\/?version>//g' | tr -d ' '| tr -d '\n')
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version=$(echo "$major.$minor.$new_patch" | sed -E 's/ //'| tr -d '\n')
          sed -i -E "s/<version>$current_version<\/version>/<version>$new_version<\/version>/" pom.xml
          echo "NEW_VERSION=$new_version" >> $GITHUB_OUTPUT

    - name: Commit updated pom.xml
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add pom.xml
        git commit -m "Update pom.xml version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set env
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: sharon088/simple_maven_java:${{ env.DATE }}  


    - name: docker run
      run: |
        docker run --rm sharon088/simple_maven_java:${{ env.DATE }}
